spring:
  application:
    name: cryptoexchange
  output:
    ansi:
      enabled: ALWAYS

external:
  api:
    url:
      price: https://api.coingecko.com/api/v3/simple/price
      supported-currencies: https://api.coingecko.com/api/v3/simple/supported_vs_currencies

fee:
  percentage: 0.01
