spring:
  application:
    name: cryptoexchange
  output:
    ansi:
      enabled: ALWAYS

external:
  api:
    coingecko:
      url:
        price: https://api.coingecko.com/api/v3/simple/price

fee:
  percentage: 0.01